"""
GitHub Issues Generator — creates GitHub Issues for each finding.
Supports dry-run mode (default) and live mode with a real token.
"""

from __future__ import annotations
import os
from typing import List, Optional, Dict
from ..models import Report, Finding


SEVERITY_LABELS = {
    "CRITICAL": "severity: critical",
    "HIGH": "severity: high",
    "MEDIUM": "severity: medium",
    "LOW": "severity: low",
    "INFO": "severity: info",
}

CATEGORY_LABELS = {
    "SQL_INJECTION": "security: sql-injection",
    "XSS": "security: xss",
    "HARDCODED_SECRET": "security: hardcoded-secret",
    "PATH_TRAVERSAL": "security: path-traversal",
    "INSECURE_DEPENDENCY": "security: insecure-dependency",
    "CRYPTO_MISUSE": "security: crypto-misuse",
}


def _format_issue_body(finding: Finding) -> str:
    """Format a GitHub Issue body from a Finding."""
    refs = "\n".join(f"- {r}" for r in finding.references) if finding.references else "_None_"
    return f"""## 🔒 Security Finding: {finding.title}

**Severity:** `{finding.severity}`  
**Category:** `{finding.category}`  
**Confidence:** `{finding.confidence}`  
**CWE:** {finding.cwe_id or 'N/A'}  

---

### 📍 Location
**File:** `{finding.location.file}`  
**Lines:** {finding.location.line_start}–{finding.location.line_end}

---

### 📋 Description
{finding.description}

---

### 💻 Code Snippet
```
{finding.code_snippet}
```

---

### ✅ Recommendation
{finding.recommendation}

---

### 🔗 References
{refs}

---
_This issue was automatically generated by the **RLM Security Analysis System**._
"""


def generate_github_issues(
    report: Report,
    repo: str,
    token: Optional[str] = None,
    dry_run: bool = True,
    min_severity: str = "MEDIUM",
) -> List[Dict]:
    """
    Create GitHub Issues for security findings.

    Args:
        report: The scan Report
        repo: GitHub repo in "owner/repo" format
        token: GitHub personal access token (or GITHUB_TOKEN env var)
        dry_run: If True, print issues but don't create them
        min_severity: Minimum severity to create issues for

    Returns:
        List of issue dicts (created or simulated)
    """
    token = token or os.environ.get("GITHUB_TOKEN")
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
    min_order = severity_order.get(min_severity, 2)

    eligible = [
        f for f in report.all_findings
        if severity_order.get(f.severity, 9) <= min_order
    ]

    created_issues = []

    if dry_run:
        print(f"\n[DRY RUN] Would create {len(eligible)} GitHub Issues in '{repo}':\n")
        for i, finding in enumerate(eligible, 1):
            print(f"  [{i}] [{finding.severity}] {finding.title}")
            print(f"       → {finding.location.file}:{finding.location.line_start}")
        print()
        return [{"dry_run": True, "title": f.title, "severity": f.severity} for f in eligible]

    # Live mode — requires PyGithub
    try:
        from github import Github, GithubException
    except ImportError:
        raise ImportError("PyGithub is required for live GitHub Issues. Run: pip install PyGithub")

    if not token:
        raise ValueError("GitHub token required for live issue creation. Set GITHUB_TOKEN env var.")

    g = Github(token)
    gh_repo = g.get_repo(repo)

    # Ensure labels exist
    _ensure_labels(gh_repo)

    for finding in eligible:
        labels = [
            SEVERITY_LABELS.get(finding.severity, ""),
            CATEGORY_LABELS.get(finding.category, "security"),
            "rlm-scanner",
        ]
        labels = [l for l in labels if l]

        try:
            issue = gh_repo.create_issue(
                title=f"[RLM] [{finding.severity}] {finding.title} — {finding.location.file}",
                body=_format_issue_body(finding),
                labels=labels,
            )
            created_issues.append({
                "number": issue.number,
                "url": issue.html_url,
                "title": finding.title,
                "severity": finding.severity,
            })
        except Exception as exc:
            print(f"Warning: Failed to create issue for {finding.title}: {exc}")

    return created_issues


def _ensure_labels(repo) -> None:
    """Create missing labels in the GitHub repo."""
    try:
        existing = {l.name for l in repo.get_labels()}
        label_config = {
            "severity: critical": "B60205",
            "severity: high": "E4E669",
            "severity: medium": "0075CA",
            "severity: low": "0E8A16",
            "security: sql-injection": "D93F0B",
            "security: xss": "FBCA04",
            "security: hardcoded-secret": "E99695",
            "security: path-traversal": "F9D0C4",
            "security: insecure-dependency": "BFD4F2",
            "security: crypto-misuse": "D4C5F9",
            "rlm-scanner": "5319E7",
        }
        for name, color in label_config.items():
            if name not in existing:
                repo.create_label(name=name, color=color)
    except Exception:
        pass  # Label creation is best-effort
